[CmdletBinding()]
param(
    [ValidateSet('uninstall', 'disable-protection', 'critical-settings')]
    [string]$Action = 'uninstall'
)

$ErrorActionPreference = 'Stop'
$ConfigPath = Join-Path $env:LOCALAPPDATA 'SentryLoom\config.json'
if (-not (Test-Path -LiteralPath $ConfigPath -PathType Leaf)) {
    exit 0
}
$Config = Get-Content -LiteralPath $ConfigPath -Raw | ConvertFrom-Json
if (-not $Config.management.enabled) {
    exit 0
}

$Node = Join-Path $env:ProgramFiles 'nodejs\node.exe'
$Cli = Join-Path $PSScriptRoot 'src\cli.js'
if (-not (Test-Path -LiteralPath $Node) -or -not (Test-Path -LiteralPath $Cli)) {
    throw 'SentryLoom maintenance authorization components are missing.'
}

function Test-MaintenancePassword([string]$Password) {
    $env:SENTRYLOOM_MAINTENANCE_PASSWORD = $Password
    $env:SENTRYLOOM_MAINTENANCE_ACTION = $Action
    try {
        $Output = & $Node `
            --disable-warning=ExperimentalWarning `
            $Cli `
            hq maintenance-authorize-env 2>&1 | Out-String
        return @{
            Accepted = $LASTEXITCODE -eq 0
            Message = ($Output -replace 'SentryLoom error:\s*', '').Trim()
        }
    } finally {
        $env:SENTRYLOOM_MAINTENANCE_PASSWORD = $null
        $env:SENTRYLOOM_MAINTENANCE_ACTION = $null
        $Password = $null
    }
}

$ProvidedPassword = [string]$env:SENTRYLOOM_MAINTENANCE_PASSWORD
if ($ProvidedPassword) {
    $Result = Test-MaintenancePassword $ProvidedPassword
    exit $(if ($Result.Accepted) { 0 } else { 1 })
}

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[Windows.Forms.Application]::EnableVisualStyles()

for ($Attempt = 1; $Attempt -le 3; $Attempt++) {
    $Form = New-Object Windows.Forms.Form
    $Form.Text = 'SentryLoom maintenance authorization'
    $Form.StartPosition = 'CenterScreen'
    $Form.FormBorderStyle = 'FixedDialog'
    $Form.MaximizeBox = $false
    $Form.MinimizeBox = $false
    $Form.ClientSize = New-Object Drawing.Size(520, 205)
    $Form.TopMost = $true

    $Heading = New-Object Windows.Forms.Label
    $Heading.Text = 'Administrator approval required'
    $Heading.Font = New-Object Drawing.Font('Segoe UI Semibold', 13)
    $Heading.AutoSize = $true
    $Heading.Location = New-Object Drawing.Point(22, 18)
    $Form.Controls.Add($Heading)

    $Description = New-Object Windows.Forms.Label
    $Description.Text = 'Enter a current one-time maintenance password generated by SentryLoom HQ. The password expires automatically and can be revoked by an HQ administrator.'
    $Description.Size = New-Object Drawing.Size(475, 48)
    $Description.Location = New-Object Drawing.Point(24, 54)
    $Form.Controls.Add($Description)

    $PasswordBox = New-Object Windows.Forms.TextBox
    $PasswordBox.UseSystemPasswordChar = $true
    $PasswordBox.Size = New-Object Drawing.Size(472, 28)
    $PasswordBox.Location = New-Object Drawing.Point(24, 108)
    $Form.Controls.Add($PasswordBox)

    $Cancel = New-Object Windows.Forms.Button
    $Cancel.Text = 'Cancel'
    $Cancel.DialogResult = [Windows.Forms.DialogResult]::Cancel
    $Cancel.Size = New-Object Drawing.Size(100, 32)
    $Cancel.Location = New-Object Drawing.Point(288, 153)
    $Form.Controls.Add($Cancel)

    $Authorize = New-Object Windows.Forms.Button
    $Authorize.Text = 'Authorize'
    $Authorize.DialogResult = [Windows.Forms.DialogResult]::OK
    $Authorize.Size = New-Object Drawing.Size(100, 32)
    $Authorize.Location = New-Object Drawing.Point(396, 153)
    $Form.Controls.Add($Authorize)
    $Form.AcceptButton = $Authorize
    $Form.CancelButton = $Cancel

    $Form.Add_Shown({ $PasswordBox.Focus() })
    if ($Form.ShowDialog() -ne [Windows.Forms.DialogResult]::OK) {
        exit 1
    }
    $Result = Test-MaintenancePassword $PasswordBox.Text
    $PasswordBox.Text = ''
    $Form.Dispose()
    if ($Result.Accepted) {
        [Windows.Forms.MessageBox]::Show(
            'Maintenance authorization accepted. The requested operation can continue.',
            'SentryLoom',
            [Windows.Forms.MessageBoxButtons]::OK,
            [Windows.Forms.MessageBoxIcon]::Information
        ) | Out-Null
        exit 0
    }
    [Windows.Forms.MessageBox]::Show(
        $(if ($Result.Message) { $Result.Message } else { 'The maintenance password was not accepted.' }),
        'SentryLoom authorization failed',
        [Windows.Forms.MessageBoxButtons]::OK,
        [Windows.Forms.MessageBoxIcon]::Warning
    ) | Out-Null
}
exit 1
